"""Pydantic contracts. Every cross-module payload in the system is defined here."""

from egraph.schemas.document import (
    Chunk,
    DocumentChange,
    DocumentStatus,
    SourceDocument,
    content_hash,
    utcnow,
)
from egraph.schemas.graph import (
    Community,
    Entity,
    ExtractedEntity,
    ExtractedRelation,
    Extraction,
    Relation,
    ResolutionDecision,
    entity_key,
    relation_key,
)
from egraph.schemas.mutation import (
    ChurnResult,
    DirtyMark,
    GCSummary,
    GraphMutation,
    MutationKind,
    Staleness,
)
from egraph.schemas.query import (
    Answer,
    CostRecord,
    IndexStats,
    QueryMode,
    QueryRequest,
    RetrievalResult,
    RetrievedCommunity,
    RetrievedEntity,
    ScenarioResult,
)

__all__ = [
    "Answer",
    "Chunk",
    "ChurnResult",
    "Community",
    "CostRecord",
    "DirtyMark",
    "DocumentChange",
    "DocumentStatus",
    "Entity",
    "ExtractedEntity",
    "ExtractedRelation",
    "Extraction",
    "GCSummary",
    "GraphMutation",
    "IndexStats",
    "MutationKind",
    "QueryMode",
    "QueryRequest",
    "Relation",
    "ResolutionDecision",
    "RetrievalResult",
    "RetrievedCommunity",
    "RetrievedEntity",
    "ScenarioResult",
    "SourceDocument",
    "Staleness",
    "content_hash",
    "entity_key",
    "relation_key",
    "utcnow",
]
